/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PostId = IDL.Nat;
export const CommentId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FreeStuffCategory = IDL.Variant({
  'tipsAndTricks' : IDL.Null,
  'freeGamePass' : IDL.Null,
  'promoCode' : IDL.Null,
  'freeUGC' : IDL.Null,
  'general' : IDL.Null,
});
export const Time = IDL.Int;
export const UserId = IDL.Principal;
export const Post = IDL.Record({
  'id' : PostId,
  'likeCount' : IDL.Nat,
  'content' : IDL.Text,
  'author' : UserId,
  'timestamp' : Time,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const Comment = IDL.Record({
  'id' : CommentId,
  'content' : IDL.Text,
  'author' : UserId,
  'timestamp' : Time,
  'postId' : PostId,
});
export const FreeStuffPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'verified' : IDL.Bool,
  'content' : IDL.Text,
  'contentType' : IDL.Text,
  'views' : IDL.Nat,
  'link' : IDL.Opt(IDL.Text),
  'tags' : IDL.Vec(IDL.Text),
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'author' : IDL.Principal,
  'likes' : IDL.Nat,
  'expirationTime' : IDL.Opt(Time),
  'timestamp' : Time,
  'category' : FreeStuffCategory,
  'proof' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([PostId, IDL.Text], [CommentId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createFreeStuffPost' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        FreeStuffCategory,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Opt(Time),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'createOrUpdateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createPost' : IDL.Func([IDL.Text], [PostId], []),
  'deleteFreeStuffPost' : IDL.Func([IDL.Nat], [], []),
  'deletePost' : IDL.Func([PostId], [], []),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([PostId], [IDL.Vec(Comment)], ['query']),
  'getFreeStuffPosts' : IDL.Func(
      [IDL.Opt(FreeStuffCategory), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Vec(FreeStuffPost)],
      ['query'],
    ),
  'getLikeCount' : IDL.Func([PostId], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeFreeStuffPost' : IDL.Func([IDL.Nat], [], []),
  'likePost' : IDL.Func([PostId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAvatar' : IDL.Func([ExternalBlob], [], []),
  'updateFreeStuffAvailability' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'verifyFreeStuffPost' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PostId = IDL.Nat;
  const CommentId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FreeStuffCategory = IDL.Variant({
    'tipsAndTricks' : IDL.Null,
    'freeGamePass' : IDL.Null,
    'promoCode' : IDL.Null,
    'freeUGC' : IDL.Null,
    'general' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserId = IDL.Principal;
  const Post = IDL.Record({
    'id' : PostId,
    'likeCount' : IDL.Nat,
    'content' : IDL.Text,
    'author' : UserId,
    'timestamp' : Time,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const Comment = IDL.Record({
    'id' : CommentId,
    'content' : IDL.Text,
    'author' : UserId,
    'timestamp' : Time,
    'postId' : PostId,
  });
  const FreeStuffPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'verified' : IDL.Bool,
    'content' : IDL.Text,
    'contentType' : IDL.Text,
    'views' : IDL.Nat,
    'link' : IDL.Opt(IDL.Text),
    'tags' : IDL.Vec(IDL.Text),
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'author' : IDL.Principal,
    'likes' : IDL.Nat,
    'expirationTime' : IDL.Opt(Time),
    'timestamp' : Time,
    'category' : FreeStuffCategory,
    'proof' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([PostId, IDL.Text], [CommentId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createFreeStuffPost' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          FreeStuffCategory,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Opt(Time),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'createOrUpdateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createPost' : IDL.Func([IDL.Text], [PostId], []),
    'deleteFreeStuffPost' : IDL.Func([IDL.Nat], [], []),
    'deletePost' : IDL.Func([PostId], [], []),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([PostId], [IDL.Vec(Comment)], ['query']),
    'getFreeStuffPosts' : IDL.Func(
        [IDL.Opt(FreeStuffCategory), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(FreeStuffPost)],
        ['query'],
      ),
    'getLikeCount' : IDL.Func([PostId], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeFreeStuffPost' : IDL.Func([IDL.Nat], [], []),
    'likePost' : IDL.Func([PostId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAvatar' : IDL.Func([ExternalBlob], [], []),
    'updateFreeStuffAvailability' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'verifyFreeStuffPost' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };